import type { NextPage } from 'next';
import { signIn, signOut, useSession } from 'next-auth/react';
import Head from 'next/head';
import Landing from '../components/Landing';
import { trpc } from '../utils/trpc';

const Home: NextPage = () => {
    const { data: session } = useSession();
    const hello = trpc.useQuery(['example.hello', { text: 'from tRPC' }]);

    const user = trpc.useQuery([
        'user.getUser',
        { email: session?.user?.email },
    ]);

    async function handleLogin() {

        const data = await fetch(
            'http://localhost:3000/api/register/',
            {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    name: 'Izaan', phone: '123456789', password: '123456789', email: 'bhoolachodi@gmail.com'
                }),
            }
        ).then(async () => {
            signIn('credentials', {
                name: 'Izaan', phone: '123456789', password: '123456789', email: 'bhoolachodi@gmail.com', redirect: false, callbackUrl: 'http://localhost:3000/'
            })
        })
            .catch(error => {
                console.log(error)

            })


    }

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Landing />
            </main>
        </>
    );
};

export default Home;
